### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by cliffrowley** [inuscript/gulp-unzip#2]
I'm seeing an error extracting a large zip file with gulp-unzip.  First I get rather a lot of these:

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
```

And then finally this:

```
RangeError: Maximum call stack size exceeded
```

My code is very simple:

```
gulp.src(config.cef_archive_path)
    .pipe(unzip())
    .pipe(gulp.dest(config.vendor_path))
```

Is this gulp-unzip or node-unzip?

Thanks.

**Comment by ZJONSSON** [comment]
Has this now been resolved?  If not please share an updated link to a failing zip

**Comment by inuscript** [comment]
It's very old issue.  
I close it ( and reopen if same issue reported)
